services:
  - type: web
    name: wbgt-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-goes-here
    autoDeploy: true
    plan: free
    healthCheckPath: /
